"""
Microsoft Teams Group Chat Messenger

Sends formatted messages to Teams group chats via Microsoft Graph API.
"""

import requests
from typing import Dict, Any, List, Optional
import logging

logger = logging.getLogger(__name__)


class TeamsMessenger:
    """Send messages to Microsoft Teams group chats."""

    GRAPH_BASE = "https://graph.microsoft.com/v1.0"

    def __init__(self, access_token: str):
        """
        Initialize Teams messenger.

        Args:
            access_token: Microsoft Graph API access token with Chat.ReadWrite permission
        """
        self.access_token = access_token
        self.headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json"
        }

    def send_message_to_chat(self, chat_id: str, message_html: str) -> Dict[str, Any]:
        """
        Send a message to a Teams group chat.

        Args:
            chat_id: The Teams chat ID (from the chat URL)
            message_html: HTML-formatted message content

        Returns:
            Response from Microsoft Graph API
        """
        url = f"{self.GRAPH_BASE}/chats/{chat_id}/messages"

        payload = {
            "body": {
                "contentType": "html",
                "content": message_html
            }
        }

        try:
            response = requests.post(url, json=payload, headers=self.headers)
            response.raise_for_status()
            logger.info(f"Successfully sent message to Teams chat {chat_id}")
            return response.json()
        except requests.exceptions.HTTPError as e:
            logger.error(f"Failed to send Teams message: {e}")
            logger.error(f"Response: {e.response.text}")
            raise

    @staticmethod
    def format_followup_report_summary(report_data: Dict[str, Any]) -> str:
        """
        Format a follow-up report into a professional Teams message.

        Args:
            report_data: The report data from ProposalFollowupAnalyzer

        Returns:
            HTML-formatted message string
        """
        # Handle both direct report data and nested summary structure
        summary = report_data.get('summary', report_data)

        total_threads = summary.get('total_count', 0)
        needs_followup = summary.get('unanswered_count', 0) + summary.get('pending_proposals_count', 0)
        engaged = total_threads - needs_followup

        # Get threads from unanswered and pending_proposals lists
        unanswered = report_data.get('unanswered', [])
        pending_proposals = report_data.get('pending_proposals', [])
        all_threads = unanswered + pending_proposals

        # Sort by expected_revenue descending
        top_opportunities = sorted(
            all_threads,
            key=lambda x: x.get('expected_revenue', 0),
            reverse=True
        )[:5]  # Top 5

        # Build HTML message
        html = f"""
<h2>📊 Daily Proposal Follow-up Report</h2>

<p><strong>Summary:</strong></p>
<ul>
    <li><strong>{needs_followup}</strong> proposals need follow-up (no response in 3+ days)</li>
    <li><strong>{engaged}</strong> active conversations</li>
    <li><strong>{total_threads}</strong> total email threads tracked</li>
</ul>

<h3>🔥 Top Opportunities Needing Follow-up:</h3>
"""

        if top_opportunities:
            html += "<ol>"
            for opp in top_opportunities:
                company = opp.get('partner_name', 'Unknown Company')
                value = opp.get('expected_revenue', 0)
                stage = opp.get('stage', 'Unknown')
                days_since = opp.get('days_since_last_response', 0)

                html += f"""
    <li>
        <strong>{company}</strong> - AED {value:,.0f}<br/>
        <em>Stage:</em> {stage} | <em>Last contact:</em> {days_since} days ago
    </li>
"""
            html += "</ol>"
        else:
            html += "<p><em>No opportunities currently need follow-up.</em></p>"

        html += """
<hr/>
<p><em>🤖 Automated report generated by PrezLab Lead Automation System</em></p>
"""

        return html

    @staticmethod
    def extract_chat_id_from_url(teams_url: str) -> Optional[str]:
        """
        Extract chat ID from a Teams chat URL.

        Example URL:
        https://teams.microsoft.com/l/chat/19:1d7fae90086342a49e12a433576697c7@thread.v2/conversations?...

        Returns:
            The chat ID (e.g., "19:1d7fae90086342a49e12a433576697c7@thread.v2")
        """
        import re

        # Pattern: /chat/{chatId}/
        match = re.search(r'/chat/([^/]+)/', teams_url)
        if match:
            return match.group(1)

        return None
